name: build

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "src/**"
      - "xmake.lua"
      - "xmake-rules.lua"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  xmake:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"

      - name: Configure
        run: xmake config -y --mode=${{ matrix.mode }}

      - name: Build
        run: xmake build -y -vD
