name: build

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "src/**"
      - "xmake.lua"
      - "xmake-rules.lua"
  pull_request:
    branches: [ main ]

jobs:
  xmake:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - releasedbg
        toolchain:
          - msvc
          - clang-cl
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"
          actions-cache-folder: ".xmake-cache"
          build-cache: true
          build-cache-key: ${{ matrix.mode }}-${{ matrix.toolchain }}
          package-cache: true
          package-cache-key: ${{ matrix.mode }}-${{ matrix.toolchain }}

      - name: config
        run: xmake config -y --mode=${{ matrix.mode }} --policies=build.ccache:y --toolchain=${{ matrix.toolchain }}

      - name: build
        run: xmake build -y -vD
